{"name": "test_search_input[chromium]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <Suites.Game.game_search.InputTest object at 0x0000021FFC7C7770>\n\n    @allure.step('Confirm login')\n    def press_confirm_log_in_button(self):\n        try:\n>           self.confirm_log_in_button.click()\n\nSuites\\Base\\BaseSetUp.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:14851: in click\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_locator.py:153: in click\n    return await self._frame.click(self._selector, strict=True, **params)\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:488: in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x0000021FFBD93B00>, cb = <function Channel.send.<locals>.<lambda> at 0x0000021FFC70A2A0>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nE           Call log:\nE           waiting for locator(\"//button[contains(@class, 'min-w-full') and contains(text(),'Log in')]\")\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:513: TimeoutError\n\nThe above exception was the direct cause of the following exception:\n\nself = <Suites.Game.game_search.InputTest object at 0x0000021FFC7C7770>\n\n    def set_up(self):\n        try:\n>           super().set_up()\n\nSuites\\Game\\game_search.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nSuites\\Base\\BaseSetUp.py:81: in set_up\n    self.press_confirm_log_in_button()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Suites.Game.game_search.InputTest object at 0x0000021FFC7C7770>\n\n    @allure.step('Confirm login')\n    def press_confirm_log_in_button(self):\n        try:\n            self.confirm_log_in_button.click()\n            time.sleep(5)\n            allure.attach(self.page.screenshot(), name='Log in button pressed',\n                          attachment_type=allure.attachment_type.PNG)\n            self.page.goto('https://tombriches.com/')\n    \n        except Exception as e:\n            allure.attach(self.page.screenshot(), name='Log in button is not pressed',\n                          attachment_type=allure.attachment_type.PNG)\n>           raise AssertionError from e\nE           AssertionError\n\nSuites\\Base\\BaseSetUp.py:64: AssertionError\n\nThe above exception was the direct cause of the following exception:\n\npage = <Page url='https://tombriches.com/'>\n\n    @allure.suite(\"Games suite\")\n    def test_search_input(page):\n        search = InputTest(page)\n>       search.set_up()\n\ntest_tr_smoke.py:68: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Suites.Game.game_search.InputTest object at 0x0000021FFC7C7770>\n\n    def set_up(self):\n        try:\n            super().set_up()\n        except Exception as e:\n            allure.attach(self.page.screenshot(), name='Set up failed', attachment_type=allure.attachment_type.PNG)\n>           raise AssertionError from e\nE           AssertionError\n\nSuites\\Game\\game_search.py:14: AssertionError"}, "steps": [{"name": "Press on Log in button", "status": "passed", "attachments": [{"name": "Log in button pressed", "source": "9392fa77-8c7b-49a2-bb42-0e33e51d0752-attachment.png", "type": "image/png"}], "start": 1714566499892, "stop": 1714566500209}, {"name": "Enter credentials", "status": "passed", "attachments": [{"name": "E-mail field filled", "source": "73d194d8-033c-4845-a605-9a9881b2e497-attachment.png", "type": "image/png"}, {"name": "Password field filled", "source": "bb9b82b5-e714-4463-9e02-8bef91e9e2e1-attachment.png", "type": "image/png"}], "start": 1714566500210, "stop": 1714566500613}, {"name": "Confirm login", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\User\\Desktop\\Automation\\TR_Smoke\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\Desktop\\Automation\\TR_Smoke\\Suites\\Base\\BaseSetUp.py\", line 64, in press_confirm_log_in_button\n    raise AssertionError from e\n"}, "attachments": [{"name": "Log in button is not pressed", "source": "97b7b049-32d9-453b-a20f-b8171e051825-attachment.png", "type": "image/png"}], "start": 1714566500614, "stop": 1714566530797}], "attachments": [{"name": "Page open", "source": "828cc810-4b58-4de6-b719-cb419c646ae6-attachment.png", "type": "image/png"}, {"name": "Set up failed", "source": "8b8c2a68-d3f9-4e1d-b06d-28124ce7348c-attachment.png", "type": "image/png"}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1714566497512, "stop": 1714566530966, "uuid": "50b6c707-fbed-48d8-bdc0-ace0fa02a645", "historyId": "6c711df0a1d4a7648f406b0b01f99c9f", "testCaseId": "89adc75aec5daa40375764ce97c926c3", "fullName": "test_tr_smoke#test_search_input", "labels": [{"name": "suite", "value": "Games suite"}, {"name": "host", "value": "DESKTOP-EFHMBBJ"}, {"name": "thread", "value": "25980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_tr_smoke"}]}